### ISSUE TITLE
request: ability to hide logs?

### ISSUE THREAD

**Issue by miclgael** [jackgllghr/PlayniteEmudeck#2]
Thanks for the great add-on, Jack! 

## Context

EmuDeck by default adds ~100s of emulator folders for systems I don't own, so I remove them. 

## Issue

When using `PlayniteEmudeck`, the system logs every time it cannot find one of those missing folders. Adding up to hundreds of messages in the alerts pane. 

## Proposal

Maybe mine is a unique case, but I was wondering if there could be a checkbox to suppress those messages? 
or perhaps, summarise missing emulator messages into a single log?

**Comment by jackgllghr** [comment]
Thanks for using it! Sounds like a big alright, I'll try and get it fixed this weekend.

The last code I've written(but still working on) is a series of toggles in the Add-On settings to let you choose which emulators you want to use (similar to Steam Rom Manager). I'll get that finished  as soon as I can, that should save you having to delete them 😊

**Comment by jackgllghr** [comment]
Closing, but will fix in:
https://github.com/jackgllghr/PlayniteEmudeck/issues/7
