### ISSUE TITLE
Adding Genesis / Mega Drive

### ISSUE THREAD

**Issue by RM81** [jackgllghr/PlayniteEmudeck#4]
First, I want to thank you for this. It works amazingly.

I'm trying to add  Sega Genesis / Mega Drive to Playnite. I assumed that because it uses the same emulator as Master System and Game Gear, I could copy the info and change the names, but it doesn't recognize it. Is there something I am missing?

**Comment by jdin** [comment]
The same question. Can you please share emulator configuration for genesis/megadrive?

**Comment by jdin** [comment]
I think I have got it. `Library - Configure Emulators`. 
Emulators tab: just copy Game Gear and change to something like this (Although problably supported file types are not fully correct here :) I add mostly zip files):  

![image](https://github.com/jackgllghr/PlayniteEmudeck/assets/92567/e2f5a3f9-1cbf-4673-9689-3716830aa9ad)

And Autoscan Configuration can be something like this: 

![image](https://github.com/jackgllghr/PlayniteEmudeck/assets/92567/b14f1590-d339-4c7a-845b-72542dd0c49f)

**Comment by jackgllghr** [comment]
> First, I want to thank you for this. It works amazingly.
> 
> 
> 
> I'm trying to add  Sega Genesis / Mega Drive to Playnite. I assumed that because it uses the same emulator as Master System and Game Gear, I could copy the info and change the names, but it doesn't recognize it. Is there something I am missing?

My apologies, I'm only seeing this now. Yeah as Sergey said above,all this plugin really does is configure the emulators in Library > Configure Emulators so you can always edit the config there. I'll try and take a look as to why Genesis / Megadrive isn't there, I thought it was one of the RetroArch emulators 🤔

**Comment by jackgllghr** [comment]
> I think I have got it. `Library - Configure Emulators`. 
> 
> Emulators tab: just copy Game Gear and change to something like this (Although problably supported file types are not fully correct here :) I add mostly zip files):  
> 
> 
> 
> ![image](https://github.com/jackgllghr/PlayniteEmudeck/assets/92567/e2f5a3f9-1cbf-4673-9689-3716830aa9ad)
> 
> 
> 
> And Autoscan Configuration can be something like this: 
> 
> 
> 
> ![image](https://github.com/jackgllghr/PlayniteEmudeck/assets/92567/b14f1590-d339-4c7a-845b-72542dd0c49f)
> 
> 

Thanks for adding this, I'll take a look as to why it's not adding Genesis by default, I'm pretty sure it was working for me at one point but maybe something changed on the Emudeck side

**Comment by RM81** [comment]
I had tried that, except I copied the Master System instead of Game Gear. This time, however, it worked. Thanks for the help.

**Comment by jackgllghr** [comment]
Thanks for catching this, I'm ashamed as I loved my Mega Drive, it got me into gaming in the first place! It's in the new release now
